version: "3.3"

networks:

    opencbr-openhim-net:
    opencbr-net:
    openhim-core-mongo-net:
    openhim-console-core-net:
    openhim-mediator-openempi-net:
    openhim-mediator-openshr-openmrs-net:
    openempi-postgres-net:
    openshr-openmrs-mysql-net:
    openshr-openxds-postgres-net:
    openshr-openmrs-openxds-net:
    openshr-openmrs-dhis2-net:
    dhis2-postgres-net:

services:

    #==================== OpenCBR ====================
    opencbr-mysql:
        image: mysql/mysql-server:5.6
        container_name: opencbr-mysql
        volumes:
            - ./opencbr/openmrs_db.sql:/docker-entrypoint-initdb.d/openmrs_db.sql
            - ./opencbr/openmrs_db_config.sql:/docker-entrypoint-initdb.d/openmrs_db_config.sql
        env_file:
            - opencbr/db.env
        ports:
            - "3307:3306"
        networks:
          - opencbr-net
    opencbr-openmrs:
        image: tomcat:7-jre7-alpine
        container_name: opencbr-openmrs
        build:
            context: .
            dockerfile: opencbr/Dockerfile
        depends_on:
            - opencbr-mysql
        volumes:
            - ./opencbr/setenv.sh:/usr/local/tomcat/bin/setenv.sh
            - ./opencbr/openmrs.war:/usr/local/tomcat/webapps/openmrs.war
            - ./opencbr/openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
            - ./opencbr/modules:/root/.OpenMRS/modules
        ports:
            - "8081:8080"
        networks:
            - opencbr-net
            - opencbr-openhim-net


    #==================== OpenHIM and the XDS mediator ==================
    mongo:
        container_name: openhim-mongo
        image: mongo:3.4
        ports:
            - "27017:27017"
        volumes:
            - ./openhim/openhim_db.gz:/openhim_db.gz
            - ./openhim/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
        networks:
            - openhim-core-mongo-net
        logging:
            driver: none

    openhim-core:
        image: wluyima/openhim-core
        container_name: openhim-core
        env_file:
            - openhim/db.env
        volumes:
            - ./openhim/core-config.json:/usr/src/app/config/default.json
            - ./openhim/xds-mediator.properties:/usr/src/app/mediator/xds-mediator.properties
        ports:
            - "5000:5000"
            - "5001:5001"
            - "5002:5002"
            - "5050:5050"
            - "5051:5051"
            - "5053:5053"
            - "7788:7788"
        depends_on:
            - mongo
        networks:
            - opencbr-openhim-net
            - openhim-core-mongo-net
            - openhim-console-core-net
            - openhim-mediator-openempi-net
            - openhim-mediator-openshr-openmrs-net

    openhim-console:
        container_name: openhim-console
        image: jembi/openhim-console
        ports:
            - "80:80"
        volumes:
            - ./openhim/console-config.json:/usr/share/nginx/html/config/default.json
        depends_on:
            - openhim-core
        networks:
            - openhim-console-core-net


    #==================== OpenEMPI ==================
    openempi-postgres:
        image: postgres:9.6
        container_name: openempi-postgres
        env_file:
            - openempi/db.env
        networks:
            - openempi-postgres-net

    openempi:
        image: wluyima/openempi
        container_name: openempi
        env_file:
            - openempi/db.env
        volumes:
            - ./openempi/configure_db.sql:/usr/share/openempi/configure_db.sql
        ports:
            - "8082:8080"
            - "3600:3600"
        networks:
            - openhim-mediator-openempi-net
            - openempi-postgres-net
        stdin_open: true
        tty: true


    #==================== OpenSHR ==================
    openshr-mysql:
        image: mysql/mysql-server:5.6
        container_name: openshr-mysql
        env_file:
            - openshr/db.env
        volumes:
            - ./openshr/openmrs_db.sql:/docker-entrypoint-initdb.d/openmrs_db.sql
            - ./openshr/openmrs_db_config.sql:/docker-entrypoint-initdb.d/openmrs_db_config.sql
        ports:
            - "3308:3306"
        networks:
          - openshr-openmrs-mysql-net
          
    postgresql-openxds:
        image: postgres:9.6
        container_name: postgresql-openxds
        networks:
            - openshr-openxds-postgres-net

    openshr-openmrs:
        image: tomcat:7.0-jre7-alpine
        container_name: openshr-openmrs
        depends_on:
            - openshr-mysql
        volumes:
            - ./openshr/openmrs.war:/usr/local/tomcat/webapps/openmrs.war
            - ./openshr/openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
            - ./openshr/modules:/root/.OpenMRS/modules
        ports:
            - "8083:8080"
        networks:
            - openshr-openmrs-mysql-net
            - openhim-mediator-openshr-openmrs-net
            - openshr-openmrs-openxds-net
            - openshr-openmrs-dhis2-net
            
    openshr-openxds:
        image: uwitech/openxds
        container_name: openshr-openxds
        volumes:
            - ./openshr/XdsCodes.xml:/opt/openxds/conf/actors/XdsCodes.xml
        ports:
            - "8010:8010"
            - "8020:8020"
        depends_on:
            - postgresql-openxds
        networks:
            - openshr-openxds-postgres-net
            - openshr-openmrs-openxds-net


    #==================== DHIS2 ==================
    dhis2-postgres:
        image: postgres:9.6
        container_name: dhis2-postgres
        env_file:
            - dhis2/db.env
        volumes:
            - ./dhis2/database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql
            - ./dhis2/db_data.sql:/docker-entrypoint-initdb.d/db_data.sql
        networks:
            - dhis2-postgres-net

    dhis2:
        image: dhis2/dhis2-web:2.29-tomcat7-jre8-latest
        container_name: dhis2
        env_file:
            - dhis2/db.env
        volumes:
            - ./dhis2/dhis.conf:/usr/share/dhis2/dhis.conf
            - ./dhis2/setenv.sh:/usr/local/tomcat/bin/setenv.sh
            - ./dhis2/server.xml:/usr/local/tomcat/conf/server.xml
        ports:
            - "8084:8080"
        depends_on:
            - dhis2-postgres
        networks:
            - dhis2-postgres-net
            - openshr-openmrs-dhis2-net